name: weeaxe_bot_admin
description: Local administrator console for the Minecraft music bot.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  web_socket_channel: ^3.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  stream_channel: ^2.1.4
flutter:
  uses-material-design: true
